### ISSUE TITLE
Can not load "webpack"

### ISSUE THREAD

**Issue by SteveZheng-BSFT** [ionic-team/ionic-unit-testing-example#25]
Environment: use the same package.json, and 3 test-config files with this repo.

after trying http://www.roblouie.com/article/376/ionic-2-set-up-unit-testing-the-best-way/, console shows Can not load "webpack" Error when npm test: 

07 04 2017 10:13:17.281:ERROR [preprocess]: Can not load "webpack"!
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[2] should be an object.
    at webpack (/Users/stevezheng/webstorm/hiitTool/node_modules/webpack/lib/webpack.js:19:9)
    at new Plugin (/Users/stevezheng/webstorm/hiitTool/node_modules/karma-webpack/lib/karma-webpack.js:67:16)
    at invoke (/Users/stevezheng/webstorm/hiitTool/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/Users/stevezheng/webstorm/hiitTool/node_modules/di/lib/injector.js:59:20)
    at get (/Users/stevezheng/webstorm/hiitTool/node_modules/di/lib/injector.js:48:43)
    at /Users/stevezheng/webstorm/hiitTool/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/Users/stevezheng/webstorm/hiitTool/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/Users/stevezheng/webstorm/hiitTool/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/Users/stevezheng/webstorm/hiitTool/node_modules/karma/lib/preprocessor.js:55:20)
    at Array.forEach (native)
    at createPreprocessor (/Users/stevezheng/webstorm/hiitTool/node_modules/karma/lib/preprocessor.js:74:20)
    at Array.invoke (/Users/stevezheng/webstorm/hiitTool/node_modules/di/lib/injector.js:75:15)
    at get (/Users/stevezheng/webstorm/hiitTool/node_modules/di/lib/injector.js:48:43)
    at /Users/stevezheng/webstorm/hiitTool/node_modules/di/lib/injector.js:71:14
    at Array.map (native)

**Comment by jinisha** [comment]
Try npm install karma-webpack@latest --save-dev to resolve this issue

**Comment by leifwells** [comment]
@SteveZheng-BSFT Can you comment if @jinisha's comment made a difference so I might close this issue? Or if more information about this issue is available? Thanks.

**Comment by SteveZheng-BSFT** [comment]
yes, make sense, forget to close this one, thanks @jinisha @leifwells
