### ISSUE TITLE
No test was found

### ISSUE THREAD

**Issue by zebulon988** [ionic-team/ionic-unit-testing-example#65]
I ran 'npm test'.The chrome was displayed and connected. However there is no test, only displayed like below:

> Karma v1.7.0 - connected
> Chrome 60.0.3112 (Windows 10 0.0.0) is idle

My Status:
My branch is up to origin/master and at commit '5aa5b69a2f04a503fdeae47bd633293b7350ec21 '.
There is no local changes.
I have ran 'npm install'.
My global 'ionic' is 3.6.

My console log:
`
C:\Users\zelijin\code\web\ionic-unit-testing-example>npm test
ionic-unit-testing-example@0.0.1 test C:\Users\zelijin\code\web\ionic-unit-testing-example
 karma start ./test-config/karma.conf.js

webpack: Compiled successfully.
webpack: Compiling...
ts-loader: Using typescript@2.3.3 and C:\Users\zelijin\code\web\ionic-unit-testing-example\tsconfig.json
22 08 2017 18:50:33.424:WARN [karma]: No captured browser, open http://localhost:9876/

webpack: Compiled successfully.
22 08 2017 18:50:33.451:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
22 08 2017 18:50:33.453:INFO [launcher]: Launching browser Chrome with unlimited concurrency
22 08 2017 18:50:33.951:INFO [launcher]: Starting browser Chrome
22 08 2017 18:50:39.151:INFO [Chrome 60.0.3112 (Windows 10 0.0.0)]: Connected on socket f0EHW9GoLj6OYj9rAAAA with id 96719920
Chrome 60.0.3112 (Windows 10 0.0.0) ERROR
  Uncaught ReferenceError: jasmine is not defined
  at C:/Users/zelijin/code/web/ionic-unit-testing-example/node_modules/._karma-jasmine-html-reporter@0.2.2@karma-jasmine-html-reporter/src/lib/adapter.js:6
Chrome 60.0.3112 (Windows 10 0.0.0) ERROR
  Uncaught ReferenceError: jasmine is not defined
  at C:/Users/zelijin/code/web/ionic-unit-testing-example/node_modules/._karma-jasmine-html-reporter@0.2.2@karma-jasmine-html-reporter/src/lib/adapter.js:6
Chrome 60.0.3112 (Windows 10 0.0.0): Executed 0 of 0 ERROR (0.383 secs / 0 secs)`

**Comment by leifwells** [comment]
I see `Uncaught ReferenceError: jasmine is not defined` but I am wondering how that could be happening for you. 

As always, I suggest that you delete your `nodes_modules` folder and run `npm install` again on the project.

Please let us know if this works for you.

**Comment by zebulon988** [comment]
I removed dir `nodes_modules` and ran `npm install`.
Then I ran `npm test`. The console log same alright. However the chrome always display nothing test.
console log 
```
C:\Users\zelijin\code\web\ionic-unit-testing-example>npm test
> ionic-unit-testing-example@0.0.1 test C:\Users\zelijin\code\web\ionic-unit-testing-example
> karma start ./test-config/karma.conf.js

webpack: Compiled successfully.
webpack: Compiling...
ts-loader: Using typescript@2.3.3 and C:\Users\zelijin\code\web\ionic-unit-testing-example\tsconfig.json
23 08 2017 12:11:32.513:WARN [karma]: No captured browser, open http://localhost:9876/

webpack: Compiled successfully.
23 08 2017 12:11:32.532:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
23 08 2017 12:11:32.532:INFO [launcher]: Launching browser Chrome with unlimited concurrency
23 08 2017 12:11:32.806:INFO [launcher]: Starting browser Chrome
23 08 2017 12:11:35.288:INFO [Chrome 60.0.3112 (Windows 10 0.0.0)]: Connected on socket d31qFjvPD8hfdl7MAAAA with id 64401065
....
Chrome 60.0.3112 (Windows 10 0.0.0): Executed 4 of 4 SUCCESS (1.509 secs / 1.494 secs)
```
It looks there is 4 test , but chrome display nothing.
chrome dispaly:
>Karma v1.7.0 - connected
>Chrome 60.0.3112 (Windows 10 0.0.0) is idle

**Comment by zebulon988** [comment]
I add a wrong test
```
it('should failed', () => expect(2).toBeNaN());
```
The console log the error, but but chrome display nothing.
```
23 08 2017 12:22:39.229:INFO [Chrome 60.0.3112 (Windows 10 0.0.0)]: Connected on socket QFjUWQMYCnvJ4xpRAAAB with id 64401065
....Chrome 60.0.3112 (Windows 10 0.0.0) Page1 should failed FAILED
        Expected 2 to be NaN.
            at UserContext.<anonymous> (webpack:///src/pages/page1/page1.spec.ts:45:38 <- karma-test-shim.js:124422:56)
            at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:391:0 <- karma-test-shim.js:107011:26)
            at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- karma-test-shim.js:106516:39)
            at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:390:0 <- karma-test-shim.js:107010:32)
            at Zone.run (webpack:///~/zone.js/dist/zone.js:141:0 <- karma-test-shim.js:106761:43)
            at UserContext.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:104:0 <- karma-test-shim.js:106215:34)
            at webpack:///~/@angular/core/@angular/core/testing.es5.js:96:0 <- karma-test-shim.js:37050:17
            at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:391:0 <- karma-test-shim.js:107011:26)
            at AsyncTestZoneSpec.onInvoke (webpack:///~/zone.js/dist/async-test.js:49:0 <- karma-test-shim.js:105754:39)
            at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:76:0 <- karma-test-shim.js:106513:39)
            at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:390:0 <- karma-test-shim.js:107010:32)
            at Zone.run (webpack:///~/zone.js/dist/zone.js:141:0 <- karma-test-shim.js:106761:43)
            at AsyncTestZoneSpec._finishCallback (webpack:///~/@angular/core/@angular/core/testing.es5.js:91:0 <- karma-test-shim.js:37045:25)
            at webpack:///~/zone.js/dist/async-test.js:38:0 <- karma-test-shim.js:105743:31
            at ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:424:0 <- karma-test-shim.js:107044:31)
            at Zone.runTask (webpack:///~/zone.js/dist/zone.js:191:0 <- karma-test-shim.js:106811:47)
            at ZoneTask.invoke (webpack:///~/zone.js/dist/zone.js:486:0 <- karma-test-shim.js:107106:38)
            at timer (webpack:///~/zone.js/dist/zone.js:1540:0 <- karma-test-shim.js:108160:29)

Chrome 60.0.3112 (Windows 10 0.0.0) Page1 should failed FAILED
        Expected 2 to be NaN.
            at UserContext.<anonymous> (webpack:///src/pages/page1/page1.spec.ts:45:38 <- karma-test-shim.js:124422:56)
            at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:391:0 <- karma-test-shim.js:107011:26)
            at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- karma-test-shim.js:106516:39)
            at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:390:0 <- karma-test-shim.js:107010:32)
            at Zone.run (webpack:///~/zone.js/dist/zone.js:141:0 <- karma-test-shim.js:106761:43)
            at UserContext.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:104:0 <- karma-test-shim.js:106215:34)
            at webpack:///~/@angular/core/@angular/core/testing.es5.js:96:0 <- karma-test-shim.js:37050:17
            at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:391:0 <- karma-test-shim.js:107011:26)
            at AsyncTestZoneSpec.onInvoke (webpack:///~/zone.js/dist/async-test.js:49:0 <- karma-test-shim.js:105754:39)
            at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:76:0 <- karma-test-shim.js:106513:39)
            at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:390:0 <- karma-test-shim.js:107010:32)
            at Zone.run (webpack:///~/zone.js/dist/zone.js:141:0 <- karma-test-shim.js:106761:43)
            at AsyncTestZoneSpec._finishCallback (webpack:///~/@angular/core/@angular/core/testing.es5.js:91:0 <- karma-test-shim.js:37045:25)
            at webpack:///~/zone.js/dist/async-test.js:38:0 <- karma-test-shim.js:105743:31
```

I refresh the chrome page.It display the error info shortly and then display nothing as before.

**Comment by leifwells** [comment]
That is exactly what should happen.

The important part is the text in your terminal window:
`Chrome 60.0.3112 (Windows 10 0.0.0): Executed 4 of 4 SUCCESS (1.509 secs / 1.494 secs)`

"SUCCESS"! You passed four tests. Notice it took 1.5 seconds? Maybe you're just not seeing the dots cross the screen while the test runs? But the browser doesn't tell you if the tests pass, it just indicates that testing is going on.

Make one of your tests fail and see what happens.

**Comment by leifwells** [comment]
Again, the browser isn't where you get the info. Watch the terminal window for that information.

**Comment by leifwells** [comment]
You can also click the debug button and see info that way as well.

**Comment by zebulon988** [comment]
I create  an angular sample , and run `ng test`. The chrome display below:
>Karma v1.7.0 - connected
>Chrome 60.0.3112 (Windows 10 0.0.0) is idle
>Jasmine 2.6.4
>3 specs, 0 failures
>AppComponent
>    should create the app
>    should have as title 'app'
>    should render title in a h1 tag

But chrome does not display these info in my ionic test.

**Comment by leifwells** [comment]
What are the differences between the two `karma.conf.js` files?

**Comment by zebulon988** [comment]
Alright , I find it.
Add this to `karma.conf.js`.
```
client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
}
```
Then chrome will display the info.

Thank you for your help!
