### ISSUE TITLE
Running test fails

### ISSUE THREAD

**Issue by tobbtechnologies** [ionic-team/ionic-unit-testing-example#77]
When I run test I get the errors below.

C:\ionic-test>npm test

> test-test@0.0.1 test C:\ionic-test
> karma start ./test-config/karma.conf.js

02 01 2018 20:51:10.747:ERROR [config]: Invalid config file!
  Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\ionic-test\test-config\webpack.test.js:1:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\ionic-test\test-config\karma.conf.js:1:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
npm ERR! Test failed.  See above for more details.

**Comment by agrosner** [comment]
npm run test?

**Comment by jphillips05** [comment]
same issue running npm run test. I am trying to run tests on the v2 branch.
