### ISSUE TITLE
Karma throws StaticInjectorError

### ISSUE THREAD

**Issue by ourarash** [ionic-team/ionic-unit-testing-example#85]
I tried to add testing to my app using this repo, but I get this error when running

`npm test`

`SocialSharing` is added to my porvider's list in app.module.ts, and the project builds and runs correctly. Removing it causes Karma to throw the same error from another plugin  in my list. 

I only get this error while testing:

```
Chrome 64.0.3282 (Mac OS X 10.13.3) MyApp Component should be created FAILED
Error: StaticInjectorError[SocialSharing]: 
  StaticInjectorError[SocialSharing]: 
    NullInjectorError: No provider for SocialSharing!
    at _NullInjector.get (webpack:///~/@angular/core/esm5/core.js:923:0 <- test-config/karma-test-shim.js:1195:19)
    at resolveToken (webpack:///~/@angular/core/esm5/core.js:1211:0 <- test-config/karma-test-shim.js:1483:24)
    at tryResolveToken (webpack:///~/@angular/core/esm5/core.js:1153:0 <- test-config/karma-test-shim.js:1425:16)
    at StaticInjector.get (webpack:///~/@angular/core/esm5/core.js:1024:0 <- test-config/karma-test-shim.js:1296:20)
    at resolveToken (webpack:///~/@angular/core/esm5/core.js:1211:0 <- test-config/karma-test-shim.js:1483:24)
    at tryResolveToken (webpack:///~/@angular/core/esm5/core.js:1153:0 <- test-config/karma-test-shim.js:1425:16)
    at StaticInjector.get (webpack:///~/@angular/core/esm5/core.js:1024:0 <- test-config/karma-test-shim.js:1296:20)
    at resolveNgModuleDep (webpack:///~/@angular/core/esm5/core.js:10585:0 <- test-config/karma-test-shim.js:10857:25)
    at NgModuleRef_.get (webpack:///~/@angular/core/esm5/core.js:11806:0 <- test-config/karma-test-shim.js:12078:16)
    at resolveDep (webpack:///~/@angular/core/esm5/core.js:12302:0 <- test-config/karma-test-shim.js:12574:45)
    at createClass (webpack:///~/@angular/core/esm5/core.js:12172:0 <- test-config/karma-test-shim.js:12444:32)
    at createDirectiveInstance (webpack:///~/@angular/core/esm5/core.js:12011:21 <- test-config/karma-test-shim.js:12283:37)
    at createViewNodes (webpack:///~/@angular/core/esm5/core.js:13449:37 <- test-config/karma-test-shim.js:13721:53)
    at createRootView (webpack:///~/@angular/core/esm5/core.js:13339:0 <- test-config/karma-test-shim.js:13611:5)
    at callWithDebugContext (webpack:///~/@angular/core/esm5/core.js:14740:25 <- test-config/karma-test-shim.js:15012:42)
    at Object.debugCreateRootView [as createRootView] (webpack:///~/@angular/core/esm5/core.js:14041:0 <- test-config/karma-test-shim.js:14313:12)
    at ComponentFactory_.create (webpack:///~/@angular/core/esm5/core.js:10960:25 <- test-config/karma-test-shim.js:11232:46)
    at initComponent (webpack:///~/@angular/core/esm5/testing.js:1086:0 <- test-config/karma-test-shim.js:79576:49)
    at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:392:0 <- test-config/karma-test-shim.js:179321:26)
    at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- test-config/karma-test-shim.js:178825:39)
    at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:391:0 <- test-config/karma-test-shim.js:179320:32)
    at Object.onInvoke (webpack:///~/@angular/core/esm5/core.js:4629:0 <- test-config/karma-test-shim.js:4901:33)
    at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:391:0 <- test-config/karma-test-shim.js:179320:32)
    at Zone.run (webpack:///~/zone.js/dist/zone.js:142:0 <- test-config/karma-test-shim.js:179071:43)
    at NgZone.run (webpack:///~/@angular/core/esm5/core.js:4446:47 <- test-config/karma-test-shim.js:4718:69)
    at TestBed.createComponent (webpack:///~/@angular/core/esm5/testing.js:1089:0 <- test-config/karma-test-shim.js:79579:58)
    at Function.TestBed.createComponent (webpack:///~/@angular/core/esm5/testing.js:808:0 <- test-config/karma-test-shim.js:79298:29)
    at UserContext.<anonymous> (webpack:///src/app/app.component.spec.ts:35:22 <- test-config/karma-test-shim.js:282489:82)
    at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:392:0 <- test-config/karma-test-shim.js:179321:26)
    at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- test-config/karma-test-shim.js:178825:39)
    at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:391:0 <- test-config/karma-test-shim.js:179320:32)
    at Zone.run (webpack:///~/zone.js/dist/zone.js:142:0 <- test-config/karma-test-shim.js:179071:43)
    at UserContext.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:104:0 <- test-config/karma-test-shim.js:178524:34)
    at webpack:///~/@angular/core/esm5/testing.js:93:0 <- test-config/karma-test-shim.js:78583:17
    at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:392:0 <- test-config/karma-test-shim.js:179321:26)
    at AsyncTestZoneSpec.onInvoke (webpack:///~/zone.js/dist/async-test.js:49:0 <- test-config/karma-test-shim.js:178008:39)
    at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:76:0 <- test-config/karma-test-shim.js:178822:39)
    at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:391:0 <- test-config/karma-test-shim.js:179320:32)
    at Zone.run (webpack:///~/zone.js/dist/zone.js:142:0 <- test-config/karma-test-shim.js:179071:43)
    at AsyncTestZoneSpec._finishCallback (webpack:///~/@angular/core/esm5/testing.js:88:0 <- test-config/karma-test-shim.js:78578:25)
    at webpack:///~/zone.js/dist/async-test.js:38:0 <- test-config/karma-test-shim.js:177997:31
    at ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:425:0 <- test-config/karma-test-shim.js:179354:31)
    at Zone.runTask (webpack:///~/zone.js/dist/zone.js:192:0 <- test-config/karma-test-shim.js:179121:47)
    at ZoneTask.invokeTask (webpack:///~/zone.js/dist/zone.js:499:0 <- test-config/karma-test-shim.js:179428:34)
    at ZoneTask.invoke (webpack:///~/zone.js/dist/zone.js:488:0 <- test-config/karma-test-shim.js:179417:48)
    at timer (webpack:///~/zone.js/dist/zone.js:2040:0 <- test-config/karma-test-shim.js:180969:29)
```

**Comment by leifwells** [comment]
The answer is in the error:
`No provider for SocialSharing!`

You have a service being injected into your class but not into your test.

When you add testing to an existing project, there can be challenges. You will have a lot of failures due to services not being injected. Please take the time to create mocks of your services to use when possible/necessary and test the actual services directly.

For more information about testing with Angular, take a look at the Angular Testing Guide: [https://angular.io/guide/testing](https://angular.io/guide/testing)
